cd bms_sara_SSPtRanking_total
start FromHPtoSSPtData300.exe
cd ..\
cd bms_sara_SSPtRanking_easy
start FromHPtoSSPtData_easy.exe
cd ..\
cd bms_sara_SSPtRanking_normal
start FromHPtoSSPtData_normal.exe
cd ..\
cd bms_sara_SSPtRanking_hard
start FromHPtoSSPtData_hard.exe
cd ..\
cd bms_sara_ClearRanking
start FromHPtoAllPlayerData300.exe
cd ..\
cd bms_sara_ClearData
start FromHPtoClearCount.exe